### ISSUE TITLE
Please build on trusty

### ISSUE THREAD

**Issue by probonopd** [emergent-design/libpsinc#11]
https://github.com/emergent-design/libpsinc/blob/2f79d3757132d3780325f76c7d2fcc26863e394a/.gitlab-ci.yml#L95

Please do not build on Xenial because it is not the oldest still-supported LTS release, which means that the resulting binaries will not run on all still-supported LTS releases. Please consider building on trusty (the currently oldest still-supported LTS release) for increased compatibility.

Thanks.

**Comment by parnham** [comment]
Firstly, thank you for linuxdeployqt, it greatly simplified the process of bundling our application!

Secondly, trusty support is not really necessary at the moment - this library is for communicating with a specialist piece of hardware which is only supported on xenial and above. The Qt application included acts as both a tool and example for the library, the AppImage was recently added for the sole purpose of providing the manufacturer with an easy to run instance for testing hardware. The AppImage version is not even deployed to the public downloads at this time.

**Comment by probonopd** [comment]
OK, thanks for the clarification.

**Comment by probonopd** [comment]
Since xenial is now the oldest still-supported Ubuntu release, it is now a reasonable target.
