### ISSUE TITLE
Initialisation issue - failed to refresh registers.

### ISSUE THREAD

**Issue by parnham** [emergent-design/libpsinc#7]
When attempting to connect to a camera the library reports:

```
Timeout
Failed to refresh registers for page 0 when connecting
```

This only seems to occur with the C# library under Windows. The same library under Linux is fine, and the native library works on both Windows and Linux.

**Comment by justen** [comment]
This is an issue in the camera firmware, not libpsinc. Please contact your hardware supplier and request a firmware update. Feel free to re-open if the problem persists after updating.
